
//List Endpoint
GET http://localhost:7100/core/purchase-unit

//Search Endpoint
###
GET http://localhost:7100/core/purchase-unit?name=metro

//Create Endpoint
###
POST http://localhost:7100/core/purchase-unit

{
  "name": "quilograma",
  "description": "Quilogramas",
  "variations": ["quilo", "kg"]
}

//Soft-delete Endpoint
###
DELETE http://localhost:7100/core/purchase-unit/2


//Get-id Endpoint
###
GET http://localhost:7100/core/purchase-unit/1
