export const ERR_PRODUCTION_PHASE_DUPLICATE = {
  code: 409,
  message: 'ERR_PRODUCTION_PHASE_DUPLICATE',
};

export const ERR_PRODUCTION_PHASE_NOT_EXISTS = {
  code: 404,
  message: 'ERR_PRODUCTION_PHASE_NOT_EXISTS',
};

export const ERR_PRODUCTION_PHASE_INACTIVE = {
  code: 400,
  message: 'ERR_PRODUCTION_PHASE_INACTIVE',
};
