Type: AWS::S3::Bucket
Properties:
  BucketName: mobly-${self:custom.stage}-${self:provider.region}-${self:service}-uploads
  PublicAccessBlockConfiguration:
    BlockPublicAcls: true
    BlockPublicPolicy: true
    IgnorePublicAcls: true
    RestrictPublicBuckets: true
  CorsConfiguration:
    CorsRules:
      -
        AllowedOrigins:
          - '*'
        AllowedHeaders:
          - '*'
        AllowedMethods:
          - GET
          - PUT
          - POST
          - DELETE
          - HEAD
        MaxAge: 3000
